baseURL: "https://www.nathanmcoleman.com/"
languageCode: en-us
title: Nathan Coleman
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  # theme
  showToc: false
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowReadingTime: false
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Nathan Coleman"
    subtitle: Advanced Weapons Engineer
    imageUrl: "home/headshot.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:natecolemancv@gmail.com"
    - name: github
      url:  https://github.com/natemcoleman
    - name: linkedin
      url:  https://www.linkedin.com/in/natemcoleman/
    - name: instagram
      url:  https://www.instagram.com/nate_theaverage/

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
